name: patent-watcher
on:
  schedule:
    - cron: "*/5 * * * 1-5"   # every 5 minutes, Mon–Fri (UTC)
  workflow_dispatch:
    inputs:
      mode:
        description: "Run mode (normal or test)"
        required: false
        default: "normal"
permissions:
  contents: write
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install requests beautifulsoup4
      - name: Run watcher
        env:
          DJANGO_USER: ${{ secrets.DJANGO_USER }}
          DJANGO_PASS: ${{ secrets.DJANGO_PASS }}
          SMTP_USER:  ${{ secrets.SMTP_USER }}
          SMTP_PASS:  ${{ secrets.SMTP_PASS }}
          TO_EMAIL:   ${{ secrets.TO_EMAIL }}

          HUBSPOT_TOKEN:      ${{ secrets.HUBSPOT_TOKEN }}
          HUBSPOT_OWNER_ID:   ${{ secrets.HUBSPOT_OWNER_ID }}     # set to 154662807
          HUBSPOT_COMPANY_ID: ${{ secrets.HUBSPOT_COMPANY_ID }}   # set to 5590029115

          MODE: ${{ github.event.inputs.mode || 'normal' }}
          # Optional if your login is at a dedicated page:
          # LOGIN_URL: https://team42api.herokuapp.com/admin/login/
          # LIST_URL:  https://team42api.herokuapp.com/passwordreset/database_models/urgentcustomeruploadedpatent/
        run: python watcher.py
      - name: Upload fetched page (for debugging)
        if: ${{ github.event.inputs.mode != 'test' }}
        uses: actions/upload-artifact@v4
        with:
          name: last-page
          path: last_page.html
      - name: Commit updated state (if changed)
        if: ${{ github.event.inputs.mode != 'test' }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -f state.json ] && [ -n "$(git status --porcelain state.json)" ]; then
            git add state.json
            git commit -m "Update state"
            git push
          else
            echo "No state changes."
          fi
